<div class="box simple_contact">
    <form id="simple_contact_form" name="simple_contact_form" action="" method="post">
        <fieldset class="group-select">
            <ul>
                <li>
                    <div class="input-box">
                        <label for="name">Name<span class="required">*</span></label><br />
                        <input name="name" id="name" title="Name" value="<?php echo $this->getUser()->getFirstname(); ?>" class="required-entry input-text" type="text" />
                    </div>
                    <div class="input-box">
                        <label for="email">Email <span class="required">*</span></label><br />
                         <input name="email" id="email" title="Email" value="<?php echo $this->getUser()->getEmail() ?>" class="required-entry input-text validate-email" type="text" />
                    </div>
                    <div class="input-box">
                        <label for="subject">Subject<span class="required">*</span></label><br />
                         <input name="subject" id="subject" title="Subject" value="" class="required-entry input-text " type="text" />
                    </div>
                    <div class="input-box">
                        <label for="message">Message</label><br />
                        <textarea name="message" id="message" title="message" class="required-entry input-text" style="height:100px;" cols="50" rows="3"></textarea>
                    </div>
                </li>
            </ul>

        </fieldset>

    <div class="button-set">
    <p class="required">* Required Fields</p>
    <button class="form-button" type="submit"><span>Submit</span></button>

    </div>
    </form>

</div>