<?php  if($this->getBanners()->getFirstItem()->getBannerId()): ?>
    <div class="flexslider">
        <ul class="slides">
            <?php foreach($this->getBanners() as $banner):?>
                <li>
                    <a href="<?php echo $banner->getUrl()?>">
                        <p class="flex-caption">
                            <?php echo Mage::helper('core')->escapeHtml($banner->getTitle()) ?>    
                        </p>
                    </a>
                    <?php if(!empty($banner->getImage())): ?>
                    <a href="<?php echo $banner->getUrl() ?>">
                        <img src="<?php echo Mage::helper('ronisbtbanners/image')
                        ->init($banner, 'small_image', $banner->getImage())
                        ->resize(900, 450)
                        ->keepAspectRatio(false); ?>" width="900" height="450" alt="<?php echo Mage::helper('core')
                        ->escapeHtml($banner->getTitle()) ?>" 
                        title="<?php echo Mage::helper('core')->escapeHtml($banner->getTitle())?>">
                    </a>
                    <?php endif; ?>
                </li>
            <?php endforeach;?>
        </ul>
    </div>
<?php endif; ?>